### ISSUE TITLE
无限获取图片

### ISSUE THREAD

**Issue by hanxiang-li** [xiongbao/we.dog#1]
左上角的舔狗图片  弄成一个GIF不好么？ 无限循环  发送请求

**Comment by xiongbao** [comment]
如果你认真看代码这并不是实现左上LOGO动图的，LOGO的狗本就是.gif。这里是为了实现动态的Favicon，也就是浏览器Tab处的小ICON，当前只有Firefox支持.gif的favicon，所以采用这种曲线救国的方案实现，请求已缓存，并不会造成过多资源损耗。当然这特效没什么卵用，你大可去掉就是。
